ALTER TABLE tasks
    ADD COLUMN category ENUM('STUDY', 'WORK', 'PERSONAL') DEFAULT 'PERSONAL',
    ADD COLUMN priority ENUM('LOW', 'MEDIUM', 'HIGH') DEFAULT 'MEDIUM',
    ADD COLUMN deadline DATETIME NULL;